import pandas as pd

if __name__ == '__main__':
    # Read CSV and skip the first row (just comments)
    dset = pd.read_csv('./datasets/Ausgrid/data/2010-2011 Solar home electricity data.csv', skiprows=1)
    
    # Filter the rows with electricity generation data
    # GG= Gross Generation for electricity generated by the solar system with a gross 
    # metering configuration, measured separately to household loads
    dset = dset[dset['Consumption Category'] == 'GG']

    #Filter the cols of interest
    cols = ['Postcode']
    dset = dset[cols]

    #Get the Postcodes
    postcodes = dset['Postcode'].drop_duplicates().to_list()

    df = pd.read_csv('./script_results/solar_hours_by_postcode.csv')
    for postcode in postcodes:
        for DT_prefix in range(100, 830 + 1):
            half_hours = range(1, 48 + 1)
            for half_hour in half_hours:
                DT = DT_prefix * 100 + half_hour
                df2 = df[(df.postcode == postcode) & (df.DT == DT)]
                if df2.size == 0:
                    print(str(postcode) + " " + str(DT) + " is not present")
        print(str(postcode) + " completed")