"""
@Author: Raúl Javierre
@Date: 26/05/2021

It tests the src/detectors/Detector's methods
"""

import io
import unittest
from parameterized import parameterized
from src.detectors.Detector import Detector
from src.detectors.DetectorFactory import DetectorFactory
from random import randrange
import pandas as pd
import os
from contextlib import redirect_stdout


NUMBER_OF_ROWS_TESTING = 5040
ELECTRICITY_METERID = 1540
GAS_METERID = 1838
NUMBER_OF_ROWS_GAS_TRAINING = 19824
NUMBER_OF_ROWS_ELECTRICITY_TRAINING = 20160


class TestDetector(unittest.TestCase):

    def testThatWeCantInstantiateAbstractDetector(self):
        self.assertRaises(TypeError, Detector)

    # Using detectors that do not override get_training_dataset
    @parameterized.expand([
        ["ARIMA", "electricity"],
        ["ARIMA", "gas"],
        ["ARIMAX", "electricity"],
        ["ARIMAX", "gas"],
        ["FisherJenks", "electricity"],
        ["FisherJenks", "gas"],
        ["IsolationForest", "electricity"],
        ["IsolationForest", "gas"],
        ["JSD", "electricity"],
        ["JSD", "gas"],
        ["KLD", "electricity"],
        ["KLD", "gas"],
        ["K-Means", "electricity"],
        ["K-Means", "gas"],
        ["MiniBatchK-Means", "electricity"],
        ["MiniBatchK-Means", "gas"],
        ["TEG_Cosine_30", "electricity"],
        ["TEG_Cosine_30", "gas"],
        ["TEG_Hamming_30", "electricity"],
        ["TEG_Hamming_30", "gas"],
        ["TEG_KL_30", "electricity"],
        ["TEG_KL_30", "gas"],
        ["TEG_JS_30", "electricity"],
        ["TEG_JS_30", "gas"],
    ])
    def testIfGetTrainingDatasetWorks(self, detector, dataset):
        detector = DetectorFactory.create_detector(detector)
        if dataset == 'electricity':
            df = detector.get_training_dataset(ELECTRICITY_METERID, dataset)
            self.assertEqual(NUMBER_OF_ROWS_ELECTRICITY_TRAINING, len(df.index))
        else:
            df = detector.get_training_dataset(GAS_METERID, dataset)
            self.assertEqual(NUMBER_OF_ROWS_GAS_TRAINING, len(df.index))

    # Using detectors that do not override get_testing_dataset
    @parameterized.expand([
        ["ARIMA", "electricity", False],
        ["ARIMA", "electricity", "Avg"],
        ["ARIMA", "electricity", "FDI0"],
        ["ARIMA", "electricity", "FDI5"],
        ["ARIMA", "electricity", "FDI10"],
        ["ARIMA", "electricity", "FDI20"],
        ["ARIMA", "electricity", "FDI30"],
        ["ARIMA", "electricity", "Min-Avg"],
        ["ARIMA", "electricity", "RSA_0.5_1.5"],
        ["ARIMA", "electricity", "RSA_0.25_1.1"],
        ["ARIMA", "electricity", "Swap"],
        ["ARIMA", "gas", False],
        ["ARIMA", "gas", "Avg"],
        ["ARIMA", "gas", "FDI0"],
        ["ARIMA", "gas", "FDI5"],
        ["ARIMA", "gas", "FDI10"],
        ["ARIMA", "gas", "FDI20"],
        ["ARIMA", "gas", "FDI30"],
        ["ARIMA", "gas", "Min-Avg"],
        ["ARIMA", "gas", "RSA_0.5_1.5"],
        ["ARIMA", "gas", "RSA_0.25_1.1"],
        ["ARIMA", "gas", "Swap"],
        ["ARIMAX", "electricity", False],
        ["ARIMAX", "electricity", "Avg"],
        ["ARIMAX", "electricity", "FDI0"],
        ["ARIMAX", "electricity", "FDI5"],
        ["ARIMAX", "electricity", "FDI10"],
        ["ARIMAX", "electricity", "FDI20"],
        ["ARIMAX", "electricity", "FDI30"],
        ["ARIMAX", "electricity", "Min-Avg"],
        ["ARIMAX", "electricity", "RSA_0.5_1.5"],
        ["ARIMAX", "electricity", "RSA_0.25_1.1"],
        ["ARIMAX", "electricity", "Swap"],
        ["ARIMAX", "gas", False],
        ["ARIMAX", "gas", "Avg"],
        ["ARIMAX", "gas", "FDI0"],
        ["ARIMAX", "gas", "FDI5"],
        ["ARIMAX", "gas", "FDI10"],
        ["ARIMAX", "gas", "FDI20"],
        ["ARIMAX", "gas", "FDI30"],
        ["ARIMAX", "gas", "Min-Avg"],
        ["ARIMAX", "gas", "RSA_0.5_1.5"],
        ["ARIMAX", "gas", "RSA_0.25_1.1"],
        ["ARIMAX", "gas", "Swap"],
        ["FisherJenks", "electricity", False],
        ["FisherJenks", "electricity", "Avg"],
        ["FisherJenks", "electricity", "FDI0"],
        ["FisherJenks", "electricity", "FDI5"],
        ["FisherJenks", "electricity", "FDI10"],
        ["FisherJenks", "electricity", "FDI20"],
        ["FisherJenks", "electricity", "FDI30"],
        ["FisherJenks", "electricity", "Min-Avg"],
        ["FisherJenks", "electricity", "RSA_0.5_1.5"],
        ["FisherJenks", "electricity", "RSA_0.25_1.1"],
        ["FisherJenks", "electricity", "Swap"],
        ["FisherJenks", "gas", False],
        ["FisherJenks", "gas", "Avg"],
        ["FisherJenks", "gas", "FDI0"],
        ["FisherJenks", "gas", "FDI5"],
        ["FisherJenks", "gas", "FDI10"],
        ["FisherJenks", "gas", "FDI20"],
        ["FisherJenks", "gas", "FDI30"],
        ["FisherJenks", "gas", "Min-Avg"],
        ["FisherJenks", "gas", "RSA_0.5_1.5"],
        ["FisherJenks", "gas", "RSA_0.25_1.1"],
        ["FisherJenks", "gas", "Swap"],
        ["IsolationForest", "electricity", False],
        ["IsolationForest", "electricity", "Avg"],
        ["IsolationForest", "electricity", "FDI0"],
        ["IsolationForest", "electricity", "FDI5"],
        ["IsolationForest", "electricity", "FDI10"],
        ["IsolationForest", "electricity", "FDI20"],
        ["IsolationForest", "electricity", "FDI30"],
        ["IsolationForest", "electricity", "Min-Avg"],
        ["IsolationForest", "electricity", "RSA_0.5_1.5"],
        ["IsolationForest", "electricity", "RSA_0.25_1.1"],
        ["IsolationForest", "electricity", "Swap"],
        ["IsolationForest", "gas", False],
        ["IsolationForest", "gas", "Avg"],
        ["IsolationForest", "gas", "FDI0"],
        ["IsolationForest", "gas", "FDI5"],
        ["IsolationForest", "gas", "FDI10"],
        ["IsolationForest", "gas", "FDI20"],
        ["IsolationForest", "gas", "FDI30"],
        ["IsolationForest", "gas", "Min-Avg"],
        ["IsolationForest", "gas", "RSA_0.5_1.5"],
        ["IsolationForest", "gas", "RSA_0.25_1.1"],
        ["IsolationForest", "gas", "Swap"],
        ["JSD", "electricity", False],
        ["JSD", "electricity", "Avg"],
        ["JSD", "electricity", "FDI0"],
        ["JSD", "electricity", "FDI5"],
        ["JSD", "electricity", "FDI10"],
        ["JSD", "electricity", "FDI20"],
        ["JSD", "electricity", "FDI30"],
        ["JSD", "electricity", "Min-Avg"],
        ["JSD", "electricity", "RSA_0.5_1.5"],
        ["JSD", "electricity", "RSA_0.25_1.1"],
        ["JSD", "electricity", "Swap"],
        ["JSD", "gas", False],
        ["JSD", "gas", "Avg"],
        ["JSD", "gas", "FDI0"],
        ["JSD", "gas", "FDI5"],
        ["JSD", "gas", "FDI10"],
        ["JSD", "gas", "FDI20"],
        ["JSD", "gas", "FDI30"],
        ["JSD", "gas", "Min-Avg"],
        ["JSD", "gas", "RSA_0.5_1.5"],
        ["JSD", "gas", "RSA_0.25_1.1"],
        ["JSD", "gas", "Swap"],
        ["KLD", "electricity", False],
        ["KLD", "electricity", "Avg"],
        ["KLD", "electricity", "FDI0"],
        ["KLD", "electricity", "FDI5"],
        ["KLD", "electricity", "FDI10"],
        ["KLD", "electricity", "FDI20"],
        ["KLD", "electricity", "FDI30"],
        ["KLD", "electricity", "Min-Avg"],
        ["KLD", "electricity", "RSA_0.5_1.5"],
        ["KLD", "electricity", "RSA_0.25_1.1"],
        ["KLD", "electricity", "Swap"],
        ["KLD", "gas", False],
        ["KLD", "gas", "Avg"],
        ["KLD", "gas", "FDI0"],
        ["KLD", "gas", "FDI5"],
        ["KLD", "gas", "FDI10"],
        ["KLD", "gas", "FDI20"],
        ["KLD", "gas", "FDI30"],
        ["KLD", "gas", "Min-Avg"],
        ["KLD", "gas", "RSA_0.5_1.5"],
        ["KLD", "gas", "RSA_0.25_1.1"],
        ["KLD", "gas", "Swap"],
        ["K-Means", "electricity", False],
        ["K-Means", "electricity", "Avg"],
        ["K-Means", "electricity", "FDI0"],
        ["K-Means", "electricity", "FDI5"],
        ["K-Means", "electricity", "FDI10"],
        ["K-Means", "electricity", "FDI20"],
        ["K-Means", "electricity", "FDI30"],
        ["K-Means", "electricity", "Min-Avg"],
        ["K-Means", "electricity", "RSA_0.5_1.5"],
        ["K-Means", "electricity", "RSA_0.25_1.1"],
        ["K-Means", "electricity", "Swap"],
        ["K-Means", "gas", False],
        ["K-Means", "gas", "Avg"],
        ["K-Means", "gas", "FDI0"],
        ["K-Means", "gas", "FDI5"],
        ["K-Means", "gas", "FDI10"],
        ["K-Means", "gas", "FDI20"],
        ["K-Means", "gas", "FDI30"],
        ["K-Means", "gas", "Min-Avg"],
        ["K-Means", "gas", "RSA_0.5_1.5"],
        ["K-Means", "gas", "RSA_0.25_1.1"],
        ["K-Means", "gas", "Swap"],
        ["MiniBatchK-Means", "electricity", False],
        ["MiniBatchK-Means", "electricity", "Avg"],
        ["MiniBatchK-Means", "electricity", "FDI0"],
        ["MiniBatchK-Means", "electricity", "FDI5"],
        ["MiniBatchK-Means", "electricity", "FDI10"],
        ["MiniBatchK-Means", "electricity", "FDI20"],
        ["MiniBatchK-Means", "electricity", "FDI30"],
        ["MiniBatchK-Means", "electricity", "Min-Avg"],
        ["MiniBatchK-Means", "electricity", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "electricity", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "electricity", "Swap"],
        ["MiniBatchK-Means", "gas", False],
        ["MiniBatchK-Means", "gas", "Avg"],
        ["MiniBatchK-Means", "gas", "FDI0"],
        ["MiniBatchK-Means", "gas", "FDI5"],
        ["MiniBatchK-Means", "gas", "FDI10"],
        ["MiniBatchK-Means", "gas", "FDI20"],
        ["MiniBatchK-Means", "gas", "FDI30"],
        ["MiniBatchK-Means", "gas", "Min-Avg"],
        ["MiniBatchK-Means", "gas", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "gas", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "gas", "Swap"],
        ["TEG_Cosine_30", "electricity", False],
        ["TEG_Cosine_30", "electricity", "Avg"],
        ["TEG_Cosine_30", "electricity", "FDI0"],
        ["TEG_Cosine_30", "electricity", "FDI5"],
        ["TEG_Cosine_30", "electricity", "FDI10"],
        ["TEG_Cosine_30", "electricity", "FDI20"],
        ["TEG_Cosine_30", "electricity", "FDI30"],
        ["TEG_Cosine_30", "electricity", "Min-Avg"],
        ["TEG_Cosine_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "electricity", "Swap"],
        ["TEG_Cosine_30", "gas", False],
        ["TEG_Cosine_30", "gas", "Avg"],
        ["TEG_Cosine_30", "gas", "FDI0"],
        ["TEG_Cosine_30", "gas", "FDI5"],
        ["TEG_Cosine_30", "gas", "FDI10"],
        ["TEG_Cosine_30", "gas", "FDI20"],
        ["TEG_Cosine_30", "gas", "FDI30"],
        ["TEG_Cosine_30", "gas", "Min-Avg"],
        ["TEG_Cosine_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "gas", "Swap"],
        ["TEG_Hamming_30", "electricity", False],
        ["TEG_Hamming_30", "electricity", "Avg"],
        ["TEG_Hamming_30", "electricity", "FDI0"],
        ["TEG_Hamming_30", "electricity", "FDI5"],
        ["TEG_Hamming_30", "electricity", "FDI10"],
        ["TEG_Hamming_30", "electricity", "FDI20"],
        ["TEG_Hamming_30", "electricity", "FDI30"],
        ["TEG_Hamming_30", "electricity", "Min-Avg"],
        ["TEG_Hamming_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "electricity", "Swap"],
        ["TEG_Hamming_30", "gas", False],
        ["TEG_Hamming_30", "gas", "Avg"],
        ["TEG_Hamming_30", "gas", "FDI0"],
        ["TEG_Hamming_30", "gas", "FDI5"],
        ["TEG_Hamming_30", "gas", "FDI10"],
        ["TEG_Hamming_30", "gas", "FDI20"],
        ["TEG_Hamming_30", "gas", "FDI30"],
        ["TEG_Hamming_30", "gas", "Min-Avg"],
        ["TEG_Hamming_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "gas", "Swap"],
        ["TEG_KL_30", "electricity", False],
        ["TEG_KL_30", "electricity", "Avg"],
        ["TEG_KL_30", "electricity", "FDI0"],
        ["TEG_KL_30", "electricity", "FDI5"],
        ["TEG_KL_30", "electricity", "FDI10"],
        ["TEG_KL_30", "electricity", "FDI20"],
        ["TEG_KL_30", "electricity", "FDI30"],
        ["TEG_KL_30", "electricity", "Min-Avg"],
        ["TEG_KL_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_KL_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_KL_30", "electricity", "Swap"],
        ["TEG_KL_30", "gas", False],
        ["TEG_KL_30", "gas", "Avg"],
        ["TEG_KL_30", "gas", "FDI0"],
        ["TEG_KL_30", "gas", "FDI5"],
        ["TEG_KL_30", "gas", "FDI10"],
        ["TEG_KL_30", "gas", "FDI20"],
        ["TEG_KL_30", "gas", "FDI30"],
        ["TEG_KL_30", "gas", "Min-Avg"],
        ["TEG_KL_30", "gas", "RSA_0.5_1.5"],
        ["TEG_KL_30", "gas", "RSA_0.25_1.1"],
        ["TEG_KL_30", "gas", "Swap"],
        ["TEG_JS_30", "gas", False],
        ["TEG_JS_30", "gas", "Avg"],
        ["TEG_JS_30", "gas", "FDI0"],
        ["TEG_JS_30", "gas", "FDI5"],
        ["TEG_JS_30", "gas", "FDI10"],
        ["TEG_JS_30", "gas", "FDI20"],
        ["TEG_JS_30", "gas", "FDI30"],
        ["TEG_JS_30", "gas", "Min-Avg"],
        ["TEG_JS_30", "gas", "RSA_0.5_1.5"],
        ["TEG_JS_30", "gas", "RSA_0.25_1.1"],
        ["TEG_JS_30", "gas", "Swap"],
    ])
    def testIfGetTestingDatasetWorks(self, detector, dataset, behaviour):
        detector = DetectorFactory.create_detector(detector)
        if dataset == 'electricity':
            df = detector.get_testing_dataset(behaviour, ELECTRICITY_METERID, dataset)
            self.assertEqual(NUMBER_OF_ROWS_TESTING, len(df.index))
        else:
            df = detector.get_testing_dataset(behaviour, GAS_METERID, dataset)
            self.assertEqual(NUMBER_OF_ROWS_TESTING, len(df.index))

    @parameterized.expand([
        ["ARIMA", "electricity", False],
        ["ARIMA", "electricity", "Avg"],
        ["ARIMA", "electricity", "FDI0"],
        ["ARIMA", "electricity", "FDI5"],
        ["ARIMA", "electricity", "FDI10"],
        ["ARIMA", "electricity", "FDI20"],
        ["ARIMA", "electricity", "FDI30"],
        ["ARIMA", "electricity", "Min-Avg"],
        ["ARIMA", "electricity", "RSA_0.5_1.5"],
        ["ARIMA", "electricity", "RSA_0.25_1.1"],
        ["ARIMA", "electricity", "Swap"],
        ["ARIMA", "gas", False],
        ["ARIMA", "gas", "Avg"],
        ["ARIMA", "gas", "FDI0"],
        ["ARIMA", "gas", "FDI5"],
        ["ARIMA", "gas", "FDI10"],
        ["ARIMA", "gas", "FDI20"],
        ["ARIMA", "gas", "FDI30"],
        ["ARIMA", "gas", "Min-Avg"],
        ["ARIMA", "gas", "RSA_0.5_1.5"],
        ["ARIMA", "gas", "RSA_0.25_1.1"],
        ["ARIMA", "gas", "Swap"],
        ["ARIMAX", "electricity", False],
        ["ARIMAX", "electricity", "Avg"],
        ["ARIMAX", "electricity", "FDI0"],
        ["ARIMAX", "electricity", "FDI5"],
        ["ARIMAX", "electricity", "FDI10"],
        ["ARIMAX", "electricity", "FDI20"],
        ["ARIMAX", "electricity", "FDI30"],
        ["ARIMAX", "electricity", "Min-Avg"],
        ["ARIMAX", "electricity", "RSA_0.5_1.5"],
        ["ARIMAX", "electricity", "RSA_0.25_1.1"],
        ["ARIMAX", "electricity", "Swap"],
        ["ARIMAX", "gas", False],
        ["ARIMAX", "gas", "Avg"],
        ["ARIMAX", "gas", "FDI0"],
        ["ARIMAX", "gas", "FDI5"],
        ["ARIMAX", "gas", "FDI10"],
        ["ARIMAX", "gas", "FDI20"],
        ["ARIMAX", "gas", "FDI30"],
        ["ARIMAX", "gas", "Min-Avg"],
        ["ARIMAX", "gas", "RSA_0.5_1.5"],
        ["ARIMAX", "gas", "RSA_0.25_1.1"],
        ["ARIMAX", "gas", "Swap"],
        ["FisherJenks", "electricity", False],
        ["FisherJenks", "electricity", "Avg"],
        ["FisherJenks", "electricity", "FDI0"],
        ["FisherJenks", "electricity", "FDI5"],
        ["FisherJenks", "electricity", "FDI10"],
        ["FisherJenks", "electricity", "FDI20"],
        ["FisherJenks", "electricity", "FDI30"],
        ["FisherJenks", "electricity", "Min-Avg"],
        ["FisherJenks", "electricity", "RSA_0.5_1.5"],
        ["FisherJenks", "electricity", "RSA_0.25_1.1"],
        ["FisherJenks", "electricity", "Swap"],
        ["FisherJenks", "gas", False],
        ["FisherJenks", "gas", "Avg"],
        ["FisherJenks", "gas", "FDI0"],
        ["FisherJenks", "gas", "FDI5"],
        ["FisherJenks", "gas", "FDI10"],
        ["FisherJenks", "gas", "FDI20"],
        ["FisherJenks", "gas", "FDI30"],
        ["FisherJenks", "gas", "Min-Avg"],
        ["FisherJenks", "gas", "RSA_0.5_1.5"],
        ["FisherJenks", "gas", "RSA_0.25_1.1"],
        ["FisherJenks", "gas", "Swap"],
        ["IsolationForest", "electricity", False],
        ["IsolationForest", "electricity", "Avg"],
        ["IsolationForest", "electricity", "FDI0"],
        ["IsolationForest", "electricity", "FDI5"],
        ["IsolationForest", "electricity", "FDI10"],
        ["IsolationForest", "electricity", "FDI20"],
        ["IsolationForest", "electricity", "FDI30"],
        ["IsolationForest", "electricity", "Min-Avg"],
        ["IsolationForest", "electricity", "RSA_0.5_1.5"],
        ["IsolationForest", "electricity", "RSA_0.25_1.1"],
        ["IsolationForest", "electricity", "Swap"],
        ["IsolationForest", "gas", False],
        ["IsolationForest", "gas", "Avg"],
        ["IsolationForest", "gas", "FDI0"],
        ["IsolationForest", "gas", "FDI5"],
        ["IsolationForest", "gas", "FDI10"],
        ["IsolationForest", "gas", "FDI20"],
        ["IsolationForest", "gas", "FDI30"],
        ["IsolationForest", "gas", "Min-Avg"],
        ["IsolationForest", "gas", "RSA_0.5_1.5"],
        ["IsolationForest", "gas", "RSA_0.25_1.1"],
        ["IsolationForest", "gas", "Swap"],
        ["JSD", "electricity", False],
        ["JSD", "electricity", "Avg"],
        ["JSD", "electricity", "FDI0"],
        ["JSD", "electricity", "FDI5"],
        ["JSD", "electricity", "FDI10"],
        ["JSD", "electricity", "FDI20"],
        ["JSD", "electricity", "FDI30"],
        ["JSD", "electricity", "Min-Avg"],
        ["JSD", "electricity", "RSA_0.5_1.5"],
        ["JSD", "electricity", "RSA_0.25_1.1"],
        ["JSD", "electricity", "Swap"],
        ["JSD", "gas", False],
        ["JSD", "gas", "Avg"],
        ["JSD", "gas", "FDI0"],
        ["JSD", "gas", "FDI5"],
        ["JSD", "gas", "FDI10"],
        ["JSD", "gas", "FDI20"],
        ["JSD", "gas", "FDI30"],
        ["JSD", "gas", "Min-Avg"],
        ["JSD", "gas", "RSA_0.5_1.5"],
        ["JSD", "gas", "RSA_0.25_1.1"],
        ["JSD", "gas", "Swap"],
        ["KLD", "electricity", False],
        ["KLD", "electricity", "Avg"],
        ["KLD", "electricity", "FDI0"],
        ["KLD", "electricity", "FDI5"],
        ["KLD", "electricity", "FDI10"],
        ["KLD", "electricity", "FDI20"],
        ["KLD", "electricity", "FDI30"],
        ["KLD", "electricity", "Min-Avg"],
        ["KLD", "electricity", "RSA_0.5_1.5"],
        ["KLD", "electricity", "RSA_0.25_1.1"],
        ["KLD", "electricity", "Swap"],
        ["KLD", "gas", False],
        ["KLD", "gas", "Avg"],
        ["KLD", "gas", "FDI0"],
        ["KLD", "gas", "FDI5"],
        ["KLD", "gas", "FDI10"],
        ["KLD", "gas", "FDI20"],
        ["KLD", "gas", "FDI30"],
        ["KLD", "gas", "Min-Avg"],
        ["KLD", "gas", "RSA_0.5_1.5"],
        ["KLD", "gas", "RSA_0.25_1.1"],
        ["KLD", "gas", "Swap"],
        ["K-Means", "electricity", False],
        ["K-Means", "electricity", "Avg"],
        ["K-Means", "electricity", "FDI0"],
        ["K-Means", "electricity", "FDI5"],
        ["K-Means", "electricity", "FDI10"],
        ["K-Means", "electricity", "FDI20"],
        ["K-Means", "electricity", "FDI30"],
        ["K-Means", "electricity", "Min-Avg"],
        ["K-Means", "electricity", "RSA_0.5_1.5"],
        ["K-Means", "electricity", "RSA_0.25_1.1"],
        ["K-Means", "electricity", "Swap"],
        ["K-Means", "gas", False],
        ["K-Means", "gas", "Avg"],
        ["K-Means", "gas", "FDI0"],
        ["K-Means", "gas", "FDI5"],
        ["K-Means", "gas", "FDI10"],
        ["K-Means", "gas", "FDI20"],
        ["K-Means", "gas", "FDI30"],
        ["K-Means", "gas", "Min-Avg"],
        ["K-Means", "gas", "RSA_0.5_1.5"],
        ["K-Means", "gas", "RSA_0.25_1.1"],
        ["K-Means", "gas", "Swap"],
        ["MiniBatchK-Means", "electricity", False],
        ["MiniBatchK-Means", "electricity", "Avg"],
        ["MiniBatchK-Means", "electricity", "FDI0"],
        ["MiniBatchK-Means", "electricity", "FDI5"],
        ["MiniBatchK-Means", "electricity", "FDI10"],
        ["MiniBatchK-Means", "electricity", "FDI20"],
        ["MiniBatchK-Means", "electricity", "FDI30"],
        ["MiniBatchK-Means", "electricity", "Min-Avg"],
        ["MiniBatchK-Means", "electricity", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "electricity", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "electricity", "Swap"],
        ["MiniBatchK-Means", "gas", False],
        ["MiniBatchK-Means", "gas", "Avg"],
        ["MiniBatchK-Means", "gas", "FDI0"],
        ["MiniBatchK-Means", "gas", "FDI5"],
        ["MiniBatchK-Means", "gas", "FDI10"],
        ["MiniBatchK-Means", "gas", "FDI20"],
        ["MiniBatchK-Means", "gas", "FDI30"],
        ["MiniBatchK-Means", "gas", "Min-Avg"],
        ["MiniBatchK-Means", "gas", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "gas", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "gas", "Swap"],
        ["TEG_Cosine_30", "electricity", False],
        ["TEG_Cosine_30", "electricity", "Avg"],
        ["TEG_Cosine_30", "electricity", "FDI0"],
        ["TEG_Cosine_30", "electricity", "FDI5"],
        ["TEG_Cosine_30", "electricity", "FDI10"],
        ["TEG_Cosine_30", "electricity", "FDI20"],
        ["TEG_Cosine_30", "electricity", "FDI30"],
        ["TEG_Cosine_30", "electricity", "Min-Avg"],
        ["TEG_Cosine_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "electricity", "Swap"],
        ["TEG_Cosine_30", "gas", False],
        ["TEG_Cosine_30", "gas", "Avg"],
        ["TEG_Cosine_30", "gas", "FDI0"],
        ["TEG_Cosine_30", "gas", "FDI5"],
        ["TEG_Cosine_30", "gas", "FDI10"],
        ["TEG_Cosine_30", "gas", "FDI20"],
        ["TEG_Cosine_30", "gas", "FDI30"],
        ["TEG_Cosine_30", "gas", "Min-Avg"],
        ["TEG_Cosine_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "gas", "Swap"],
        ["TEG_Hamming_30", "electricity", False],
        ["TEG_Hamming_30", "electricity", "Avg"],
        ["TEG_Hamming_30", "electricity", "FDI0"],
        ["TEG_Hamming_30", "electricity", "FDI5"],
        ["TEG_Hamming_30", "electricity", "FDI10"],
        ["TEG_Hamming_30", "electricity", "FDI20"],
        ["TEG_Hamming_30", "electricity", "FDI30"],
        ["TEG_Hamming_30", "electricity", "Min-Avg"],
        ["TEG_Hamming_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "electricity", "Swap"],
        ["TEG_Hamming_30", "gas", False],
        ["TEG_Hamming_30", "gas", "Avg"],
        ["TEG_Hamming_30", "gas", "FDI0"],
        ["TEG_Hamming_30", "gas", "FDI5"],
        ["TEG_Hamming_30", "gas", "FDI10"],
        ["TEG_Hamming_30", "gas", "FDI20"],
        ["TEG_Hamming_30", "gas", "FDI30"],
        ["TEG_Hamming_30", "gas", "Min-Avg"],
        ["TEG_Hamming_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "gas", "Swap"],
        ["TEG_KL_30", "electricity", False],
        ["TEG_KL_30", "electricity", "Avg"],
        ["TEG_KL_30", "electricity", "FDI0"],
        ["TEG_KL_30", "electricity", "FDI5"],
        ["TEG_KL_30", "electricity", "FDI10"],
        ["TEG_KL_30", "electricity", "FDI20"],
        ["TEG_KL_30", "electricity", "FDI30"],
        ["TEG_KL_30", "electricity", "Min-Avg"],
        ["TEG_KL_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_KL_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_KL_30", "electricity", "Swap"],
        ["TEG_KL_30", "gas", False],
        ["TEG_KL_30", "gas", "Avg"],
        ["TEG_KL_30", "gas", "FDI0"],
        ["TEG_KL_30", "gas", "FDI5"],
        ["TEG_KL_30", "gas", "FDI10"],
        ["TEG_KL_30", "gas", "FDI20"],
        ["TEG_KL_30", "gas", "FDI30"],
        ["TEG_KL_30", "gas", "Min-Avg"],
        ["TEG_KL_30", "gas", "RSA_0.5_1.5"],
        ["TEG_KL_30", "gas", "RSA_0.25_1.1"],
        ["TEG_KL_30", "gas", "Swap"],
        ["TEG_JS_30", "gas", False],
        ["TEG_JS_30", "gas", "Avg"],
        ["TEG_JS_30", "gas", "FDI0"],
        ["TEG_JS_30", "gas", "FDI5"],
        ["TEG_JS_30", "gas", "FDI10"],
        ["TEG_JS_30", "gas", "FDI20"],
        ["TEG_JS_30", "gas", "FDI30"],
        ["TEG_JS_30", "gas", "Min-Avg"],
        ["TEG_JS_30", "gas", "RSA_0.5_1.5"],
        ["TEG_JS_30", "gas", "RSA_0.25_1.1"],
        ["TEG_JS_30", "gas", "Swap"],
    ])
    def testIfRandomMetricsToCSVWorks(self, detector, dataset, behaviour):
        detectorObject = DetectorFactory.create_detector(detector)
        detectorObject.metrics_to_csv(randrange(10000), detector, behaviour, randrange(10), randrange(1000), randrange(2000), randrange(2000), randrange(2000), randrange(2000), 'tests_CI_' + dataset)
        df = pd.read_csv('./script_results/' + 'tests_CI_' + dataset + "_detector_comparer_results.csv")
        os.remove('./script_results/' + 'tests_CI_' + dataset + "_detector_comparer_results.csv")

        self.assertEqual(1, len(df.index))

    @parameterized.expand([
        ["ARIMA", "electricity", False],
        ["ARIMA", "electricity", "Avg"],
        ["ARIMA", "electricity", "FDI0"],
        ["ARIMA", "electricity", "FDI5"],
        ["ARIMA", "electricity", "FDI10"],
        ["ARIMA", "electricity", "FDI20"],
        ["ARIMA", "electricity", "FDI30"],
        ["ARIMA", "electricity", "Min-Avg"],
        ["ARIMA", "electricity", "RSA_0.5_1.5"],
        ["ARIMA", "electricity", "RSA_0.25_1.1"],
        ["ARIMA", "electricity", "Swap"],
        ["ARIMA", "gas", False],
        ["ARIMA", "gas", "Avg"],
        ["ARIMA", "gas", "FDI0"],
        ["ARIMA", "gas", "FDI5"],
        ["ARIMA", "gas", "FDI10"],
        ["ARIMA", "gas", "FDI20"],
        ["ARIMA", "gas", "FDI30"],
        ["ARIMA", "gas", "Min-Avg"],
        ["ARIMA", "gas", "RSA_0.5_1.5"],
        ["ARIMA", "gas", "RSA_0.25_1.1"],
        ["ARIMA", "gas", "Swap"],
        ["ARIMAX", "electricity", False],
        ["ARIMAX", "electricity", "Avg"],
        ["ARIMAX", "electricity", "FDI0"],
        ["ARIMAX", "electricity", "FDI5"],
        ["ARIMAX", "electricity", "FDI10"],
        ["ARIMAX", "electricity", "FDI20"],
        ["ARIMAX", "electricity", "FDI30"],
        ["ARIMAX", "electricity", "Min-Avg"],
        ["ARIMAX", "electricity", "RSA_0.5_1.5"],
        ["ARIMAX", "electricity", "RSA_0.25_1.1"],
        ["ARIMAX", "electricity", "Swap"],
        ["ARIMAX", "gas", False],
        ["ARIMAX", "gas", "Avg"],
        ["ARIMAX", "gas", "FDI0"],
        ["ARIMAX", "gas", "FDI5"],
        ["ARIMAX", "gas", "FDI10"],
        ["ARIMAX", "gas", "FDI20"],
        ["ARIMAX", "gas", "FDI30"],
        ["ARIMAX", "gas", "Min-Avg"],
        ["ARIMAX", "gas", "RSA_0.5_1.5"],
        ["ARIMAX", "gas", "RSA_0.25_1.1"],
        ["ARIMAX", "gas", "Swap"],
        ["FisherJenks", "electricity", False],
        ["FisherJenks", "electricity", "Avg"],
        ["FisherJenks", "electricity", "FDI0"],
        ["FisherJenks", "electricity", "FDI5"],
        ["FisherJenks", "electricity", "FDI10"],
        ["FisherJenks", "electricity", "FDI20"],
        ["FisherJenks", "electricity", "FDI30"],
        ["FisherJenks", "electricity", "Min-Avg"],
        ["FisherJenks", "electricity", "RSA_0.5_1.5"],
        ["FisherJenks", "electricity", "RSA_0.25_1.1"],
        ["FisherJenks", "electricity", "Swap"],
        ["FisherJenks", "gas", False],
        ["FisherJenks", "gas", "Avg"],
        ["FisherJenks", "gas", "FDI0"],
        ["FisherJenks", "gas", "FDI5"],
        ["FisherJenks", "gas", "FDI10"],
        ["FisherJenks", "gas", "FDI20"],
        ["FisherJenks", "gas", "FDI30"],
        ["FisherJenks", "gas", "Min-Avg"],
        ["FisherJenks", "gas", "RSA_0.5_1.5"],
        ["FisherJenks", "gas", "RSA_0.25_1.1"],
        ["FisherJenks", "gas", "Swap"],
        ["IsolationForest", "electricity", False],
        ["IsolationForest", "electricity", "Avg"],
        ["IsolationForest", "electricity", "FDI0"],
        ["IsolationForest", "electricity", "FDI5"],
        ["IsolationForest", "electricity", "FDI10"],
        ["IsolationForest", "electricity", "FDI20"],
        ["IsolationForest", "electricity", "FDI30"],
        ["IsolationForest", "electricity", "Min-Avg"],
        ["IsolationForest", "electricity", "RSA_0.5_1.5"],
        ["IsolationForest", "electricity", "RSA_0.25_1.1"],
        ["IsolationForest", "electricity", "Swap"],
        ["IsolationForest", "gas", False],
        ["IsolationForest", "gas", "Avg"],
        ["IsolationForest", "gas", "FDI0"],
        ["IsolationForest", "gas", "FDI5"],
        ["IsolationForest", "gas", "FDI10"],
        ["IsolationForest", "gas", "FDI20"],
        ["IsolationForest", "gas", "FDI30"],
        ["IsolationForest", "gas", "Min-Avg"],
        ["IsolationForest", "gas", "RSA_0.5_1.5"],
        ["IsolationForest", "gas", "RSA_0.25_1.1"],
        ["IsolationForest", "gas", "Swap"],
        ["JSD", "electricity", False],
        ["JSD", "electricity", "Avg"],
        ["JSD", "electricity", "FDI0"],
        ["JSD", "electricity", "FDI5"],
        ["JSD", "electricity", "FDI10"],
        ["JSD", "electricity", "FDI20"],
        ["JSD", "electricity", "FDI30"],
        ["JSD", "electricity", "Min-Avg"],
        ["JSD", "electricity", "RSA_0.5_1.5"],
        ["JSD", "electricity", "RSA_0.25_1.1"],
        ["JSD", "electricity", "Swap"],
        ["JSD", "gas", False],
        ["JSD", "gas", "Avg"],
        ["JSD", "gas", "FDI0"],
        ["JSD", "gas", "FDI5"],
        ["JSD", "gas", "FDI10"],
        ["JSD", "gas", "FDI20"],
        ["JSD", "gas", "FDI30"],
        ["JSD", "gas", "Min-Avg"],
        ["JSD", "gas", "RSA_0.5_1.5"],
        ["JSD", "gas", "RSA_0.25_1.1"],
        ["JSD", "gas", "Swap"],
        ["KLD", "electricity", False],
        ["KLD", "electricity", "Avg"],
        ["KLD", "electricity", "FDI0"],
        ["KLD", "electricity", "FDI5"],
        ["KLD", "electricity", "FDI10"],
        ["KLD", "electricity", "FDI20"],
        ["KLD", "electricity", "FDI30"],
        ["KLD", "electricity", "Min-Avg"],
        ["KLD", "electricity", "RSA_0.5_1.5"],
        ["KLD", "electricity", "RSA_0.25_1.1"],
        ["KLD", "electricity", "Swap"],
        ["KLD", "gas", False],
        ["KLD", "gas", "Avg"],
        ["KLD", "gas", "FDI0"],
        ["KLD", "gas", "FDI5"],
        ["KLD", "gas", "FDI10"],
        ["KLD", "gas", "FDI20"],
        ["KLD", "gas", "FDI30"],
        ["KLD", "gas", "Min-Avg"],
        ["KLD", "gas", "RSA_0.5_1.5"],
        ["KLD", "gas", "RSA_0.25_1.1"],
        ["KLD", "gas", "Swap"],
        ["K-Means", "electricity", False],
        ["K-Means", "electricity", "Avg"],
        ["K-Means", "electricity", "FDI0"],
        ["K-Means", "electricity", "FDI5"],
        ["K-Means", "electricity", "FDI10"],
        ["K-Means", "electricity", "FDI20"],
        ["K-Means", "electricity", "FDI30"],
        ["K-Means", "electricity", "Min-Avg"],
        ["K-Means", "electricity", "RSA_0.5_1.5"],
        ["K-Means", "electricity", "RSA_0.25_1.1"],
        ["K-Means", "electricity", "Swap"],
        ["K-Means", "gas", False],
        ["K-Means", "gas", "Avg"],
        ["K-Means", "gas", "FDI0"],
        ["K-Means", "gas", "FDI5"],
        ["K-Means", "gas", "FDI10"],
        ["K-Means", "gas", "FDI20"],
        ["K-Means", "gas", "FDI30"],
        ["K-Means", "gas", "Min-Avg"],
        ["K-Means", "gas", "RSA_0.5_1.5"],
        ["K-Means", "gas", "RSA_0.25_1.1"],
        ["K-Means", "gas", "Swap"],
        ["MiniBatchK-Means", "electricity", False],
        ["MiniBatchK-Means", "electricity", "Avg"],
        ["MiniBatchK-Means", "electricity", "FDI0"],
        ["MiniBatchK-Means", "electricity", "FDI5"],
        ["MiniBatchK-Means", "electricity", "FDI10"],
        ["MiniBatchK-Means", "electricity", "FDI20"],
        ["MiniBatchK-Means", "electricity", "FDI30"],
        ["MiniBatchK-Means", "electricity", "Min-Avg"],
        ["MiniBatchK-Means", "electricity", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "electricity", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "electricity", "Swap"],
        ["MiniBatchK-Means", "gas", False],
        ["MiniBatchK-Means", "gas", "Avg"],
        ["MiniBatchK-Means", "gas", "FDI0"],
        ["MiniBatchK-Means", "gas", "FDI5"],
        ["MiniBatchK-Means", "gas", "FDI10"],
        ["MiniBatchK-Means", "gas", "FDI20"],
        ["MiniBatchK-Means", "gas", "FDI30"],
        ["MiniBatchK-Means", "gas", "Min-Avg"],
        ["MiniBatchK-Means", "gas", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "gas", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "gas", "Swap"],
        ["TEG_Cosine_30", "electricity", False],
        ["TEG_Cosine_30", "electricity", "Avg"],
        ["TEG_Cosine_30", "electricity", "FDI0"],
        ["TEG_Cosine_30", "electricity", "FDI5"],
        ["TEG_Cosine_30", "electricity", "FDI10"],
        ["TEG_Cosine_30", "electricity", "FDI20"],
        ["TEG_Cosine_30", "electricity", "FDI30"],
        ["TEG_Cosine_30", "electricity", "Min-Avg"],
        ["TEG_Cosine_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "electricity", "Swap"],
        ["TEG_Cosine_30", "gas", False],
        ["TEG_Cosine_30", "gas", "Avg"],
        ["TEG_Cosine_30", "gas", "FDI0"],
        ["TEG_Cosine_30", "gas", "FDI5"],
        ["TEG_Cosine_30", "gas", "FDI10"],
        ["TEG_Cosine_30", "gas", "FDI20"],
        ["TEG_Cosine_30", "gas", "FDI30"],
        ["TEG_Cosine_30", "gas", "Min-Avg"],
        ["TEG_Cosine_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "gas", "Swap"],
        ["TEG_Hamming_30", "electricity", False],
        ["TEG_Hamming_30", "electricity", "Avg"],
        ["TEG_Hamming_30", "electricity", "FDI0"],
        ["TEG_Hamming_30", "electricity", "FDI5"],
        ["TEG_Hamming_30", "electricity", "FDI10"],
        ["TEG_Hamming_30", "electricity", "FDI20"],
        ["TEG_Hamming_30", "electricity", "FDI30"],
        ["TEG_Hamming_30", "electricity", "Min-Avg"],
        ["TEG_Hamming_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "electricity", "Swap"],
        ["TEG_Hamming_30", "gas", False],
        ["TEG_Hamming_30", "gas", "Avg"],
        ["TEG_Hamming_30", "gas", "FDI0"],
        ["TEG_Hamming_30", "gas", "FDI5"],
        ["TEG_Hamming_30", "gas", "FDI10"],
        ["TEG_Hamming_30", "gas", "FDI20"],
        ["TEG_Hamming_30", "gas", "FDI30"],
        ["TEG_Hamming_30", "gas", "Min-Avg"],
        ["TEG_Hamming_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "gas", "Swap"],
        ["TEG_KL_30", "electricity", False],
        ["TEG_KL_30", "electricity", "Avg"],
        ["TEG_KL_30", "electricity", "FDI0"],
        ["TEG_KL_30", "electricity", "FDI5"],
        ["TEG_KL_30", "electricity", "FDI10"],
        ["TEG_KL_30", "electricity", "FDI20"],
        ["TEG_KL_30", "electricity", "FDI30"],
        ["TEG_KL_30", "electricity", "Min-Avg"],
        ["TEG_KL_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_KL_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_KL_30", "electricity", "Swap"],
        ["TEG_KL_30", "gas", False],
        ["TEG_KL_30", "gas", "Avg"],
        ["TEG_KL_30", "gas", "FDI0"],
        ["TEG_KL_30", "gas", "FDI5"],
        ["TEG_KL_30", "gas", "FDI10"],
        ["TEG_KL_30", "gas", "FDI20"],
        ["TEG_KL_30", "gas", "FDI30"],
        ["TEG_KL_30", "gas", "Min-Avg"],
        ["TEG_KL_30", "gas", "RSA_0.5_1.5"],
        ["TEG_KL_30", "gas", "RSA_0.25_1.1"],
        ["TEG_KL_30", "gas", "Swap"],
        ["TEG_KL_30", "electricity", "Swap"],
        ["TEG_JS_30", "gas", False],
        ["TEG_JS_30", "gas", "Avg"],
        ["TEG_JS_30", "gas", "FDI0"],
        ["TEG_JS_30", "gas", "FDI5"],
        ["TEG_JS_30", "gas", "FDI10"],
        ["TEG_JS_30", "gas", "FDI20"],
        ["TEG_JS_30", "gas", "FDI30"],
        ["TEG_JS_30", "gas", "Min-Avg"],
        ["TEG_JS_30", "gas", "RSA_0.5_1.5"],
        ["TEG_JS_30", "gas", "RSA_0.25_1.1"],
        ["TEG_JS_30", "gas", "Swap"],
    ])
    def testIfFixedMetricsToCSVWorks(self, detector, dataset, behaviour):
        detectorObject = DetectorFactory.create_detector(detector)
        detectorObject.metrics_to_csv(9613, detector, behaviour, 11.24124, 21.4218656, 10, 5, 3, 2, 'tests_CI_' + dataset)
        df = pd.read_csv('./script_results/' + 'tests_CI_' + dataset + "_detector_comparer_results.csv")
        os.remove('./script_results/' + 'tests_CI_' + dataset + "_detector_comparer_results.csv")

        self.assertEqual(1, len(df.index))
        self.assertEqual(9613, df['meterID'][0])
        self.assertEqual(detector, df['detector'][0])
        self.assertEqual(behaviour, df['attack'][0])
        self.assertEqual(11.24124, df['time_model_creation'][0])
        self.assertEqual(21.4218656, df['time_model_prediction'][0])
        self.assertEqual(10, df['n_tp'][0])
        self.assertEqual(5, df['n_tn'][0])
        self.assertEqual(3, df['n_fp'][0])
        self.assertEqual(2, df['n_fn'][0])
        self.assertEqual(0.75, df['accuracy'][0])

    @parameterized.expand([
        ["ARIMA", "electricity", False],
        ["ARIMA", "electricity", "Avg"],
        ["ARIMA", "electricity", "FDI0"],
        ["ARIMA", "electricity", "FDI5"],
        ["ARIMA", "electricity", "FDI10"],
        ["ARIMA", "electricity", "FDI20"],
        ["ARIMA", "electricity", "FDI30"],
        ["ARIMA", "electricity", "Min-Avg"],
        ["ARIMA", "electricity", "RSA_0.5_1.5"],
        ["ARIMA", "electricity", "RSA_0.25_1.1"],
        ["ARIMA", "electricity", "Swap"],
        ["ARIMA", "gas", False],
        ["ARIMA", "gas", "Avg"],
        ["ARIMA", "gas", "FDI0"],
        ["ARIMA", "gas", "FDI5"],
        ["ARIMA", "gas", "FDI10"],
        ["ARIMA", "gas", "FDI20"],
        ["ARIMA", "gas", "FDI30"],
        ["ARIMA", "gas", "Min-Avg"],
        ["ARIMA", "gas", "RSA_0.5_1.5"],
        ["ARIMA", "gas", "RSA_0.25_1.1"],
        ["ARIMA", "gas", "Swap"],
        ["ARIMAX", "electricity", False],
        ["ARIMAX", "electricity", "Avg"],
        ["ARIMAX", "electricity", "FDI0"],
        ["ARIMAX", "electricity", "FDI5"],
        ["ARIMAX", "electricity", "FDI10"],
        ["ARIMAX", "electricity", "FDI20"],
        ["ARIMAX", "electricity", "FDI30"],
        ["ARIMAX", "electricity", "Min-Avg"],
        ["ARIMAX", "electricity", "RSA_0.5_1.5"],
        ["ARIMAX", "electricity", "RSA_0.25_1.1"],
        ["ARIMAX", "electricity", "Swap"],
        ["ARIMAX", "gas", False],
        ["ARIMAX", "gas", "Avg"],
        ["ARIMAX", "gas", "FDI0"],
        ["ARIMAX", "gas", "FDI5"],
        ["ARIMAX", "gas", "FDI10"],
        ["ARIMAX", "gas", "FDI20"],
        ["ARIMAX", "gas", "FDI30"],
        ["ARIMAX", "gas", "Min-Avg"],
        ["ARIMAX", "gas", "RSA_0.5_1.5"],
        ["ARIMAX", "gas", "RSA_0.25_1.1"],
        ["ARIMAX", "gas", "Swap"],
        ["FisherJenks", "electricity", False],
        ["FisherJenks", "electricity", "Avg"],
        ["FisherJenks", "electricity", "FDI0"],
        ["FisherJenks", "electricity", "FDI5"],
        ["FisherJenks", "electricity", "FDI10"],
        ["FisherJenks", "electricity", "FDI20"],
        ["FisherJenks", "electricity", "FDI30"],
        ["FisherJenks", "electricity", "Min-Avg"],
        ["FisherJenks", "electricity", "RSA_0.5_1.5"],
        ["FisherJenks", "electricity", "RSA_0.25_1.1"],
        ["FisherJenks", "electricity", "Swap"],
        ["FisherJenks", "gas", False],
        ["FisherJenks", "gas", "Avg"],
        ["FisherJenks", "gas", "FDI0"],
        ["FisherJenks", "gas", "FDI5"],
        ["FisherJenks", "gas", "FDI10"],
        ["FisherJenks", "gas", "FDI20"],
        ["FisherJenks", "gas", "FDI30"],
        ["FisherJenks", "gas", "Min-Avg"],
        ["FisherJenks", "gas", "RSA_0.5_1.5"],
        ["FisherJenks", "gas", "RSA_0.25_1.1"],
        ["FisherJenks", "gas", "Swap"],
        ["IsolationForest", "electricity", False],
        ["IsolationForest", "electricity", "Avg"],
        ["IsolationForest", "electricity", "FDI0"],
        ["IsolationForest", "electricity", "FDI5"],
        ["IsolationForest", "electricity", "FDI10"],
        ["IsolationForest", "electricity", "FDI20"],
        ["IsolationForest", "electricity", "FDI30"],
        ["IsolationForest", "electricity", "Min-Avg"],
        ["IsolationForest", "electricity", "RSA_0.5_1.5"],
        ["IsolationForest", "electricity", "RSA_0.25_1.1"],
        ["IsolationForest", "electricity", "Swap"],
        ["IsolationForest", "gas", False],
        ["IsolationForest", "gas", "Avg"],
        ["IsolationForest", "gas", "FDI0"],
        ["IsolationForest", "gas", "FDI5"],
        ["IsolationForest", "gas", "FDI10"],
        ["IsolationForest", "gas", "FDI20"],
        ["IsolationForest", "gas", "FDI30"],
        ["IsolationForest", "gas", "Min-Avg"],
        ["IsolationForest", "gas", "RSA_0.5_1.5"],
        ["IsolationForest", "gas", "RSA_0.25_1.1"],
        ["IsolationForest", "gas", "Swap"],
        ["JSD", "electricity", False],
        ["JSD", "electricity", "Avg"],
        ["JSD", "electricity", "FDI0"],
        ["JSD", "electricity", "FDI5"],
        ["JSD", "electricity", "FDI10"],
        ["JSD", "electricity", "FDI20"],
        ["JSD", "electricity", "FDI30"],
        ["JSD", "electricity", "Min-Avg"],
        ["JSD", "electricity", "RSA_0.5_1.5"],
        ["JSD", "electricity", "RSA_0.25_1.1"],
        ["JSD", "electricity", "Swap"],
        ["JSD", "gas", False],
        ["JSD", "gas", "Avg"],
        ["JSD", "gas", "FDI0"],
        ["JSD", "gas", "FDI5"],
        ["JSD", "gas", "FDI10"],
        ["JSD", "gas", "FDI20"],
        ["JSD", "gas", "FDI30"],
        ["JSD", "gas", "Min-Avg"],
        ["JSD", "gas", "RSA_0.5_1.5"],
        ["JSD", "gas", "RSA_0.25_1.1"],
        ["JSD", "gas", "Swap"],
        ["KLD", "electricity", False],
        ["KLD", "electricity", "Avg"],
        ["KLD", "electricity", "FDI0"],
        ["KLD", "electricity", "FDI5"],
        ["KLD", "electricity", "FDI10"],
        ["KLD", "electricity", "FDI20"],
        ["KLD", "electricity", "FDI30"],
        ["KLD", "electricity", "Min-Avg"],
        ["KLD", "electricity", "RSA_0.5_1.5"],
        ["KLD", "electricity", "RSA_0.25_1.1"],
        ["KLD", "electricity", "Swap"],
        ["KLD", "gas", False],
        ["KLD", "gas", "Avg"],
        ["KLD", "gas", "FDI0"],
        ["KLD", "gas", "FDI5"],
        ["KLD", "gas", "FDI10"],
        ["KLD", "gas", "FDI20"],
        ["KLD", "gas", "FDI30"],
        ["KLD", "gas", "Min-Avg"],
        ["KLD", "gas", "RSA_0.5_1.5"],
        ["KLD", "gas", "RSA_0.25_1.1"],
        ["KLD", "gas", "Swap"],
        ["K-Means", "electricity", False],
        ["K-Means", "electricity", "Avg"],
        ["K-Means", "electricity", "FDI0"],
        ["K-Means", "electricity", "FDI5"],
        ["K-Means", "electricity", "FDI10"],
        ["K-Means", "electricity", "FDI20"],
        ["K-Means", "electricity", "FDI30"],
        ["K-Means", "electricity", "Min-Avg"],
        ["K-Means", "electricity", "RSA_0.5_1.5"],
        ["K-Means", "electricity", "RSA_0.25_1.1"],
        ["K-Means", "electricity", "Swap"],
        ["K-Means", "gas", False],
        ["K-Means", "gas", "Avg"],
        ["K-Means", "gas", "FDI0"],
        ["K-Means", "gas", "FDI5"],
        ["K-Means", "gas", "FDI10"],
        ["K-Means", "gas", "FDI20"],
        ["K-Means", "gas", "FDI30"],
        ["K-Means", "gas", "Min-Avg"],
        ["K-Means", "gas", "RSA_0.5_1.5"],
        ["K-Means", "gas", "RSA_0.25_1.1"],
        ["K-Means", "gas", "Swap"],
        ["MiniBatchK-Means", "electricity", False],
        ["MiniBatchK-Means", "electricity", "Avg"],
        ["MiniBatchK-Means", "electricity", "FDI0"],
        ["MiniBatchK-Means", "electricity", "FDI5"],
        ["MiniBatchK-Means", "electricity", "FDI10"],
        ["MiniBatchK-Means", "electricity", "FDI20"],
        ["MiniBatchK-Means", "electricity", "FDI30"],
        ["MiniBatchK-Means", "electricity", "Min-Avg"],
        ["MiniBatchK-Means", "electricity", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "electricity", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "electricity", "Swap"],
        ["MiniBatchK-Means", "gas", False],
        ["MiniBatchK-Means", "gas", "Avg"],
        ["MiniBatchK-Means", "gas", "FDI0"],
        ["MiniBatchK-Means", "gas", "FDI5"],
        ["MiniBatchK-Means", "gas", "FDI10"],
        ["MiniBatchK-Means", "gas", "FDI20"],
        ["MiniBatchK-Means", "gas", "FDI30"],
        ["MiniBatchK-Means", "gas", "Min-Avg"],
        ["MiniBatchK-Means", "gas", "RSA_0.5_1.5"],
        ["MiniBatchK-Means", "gas", "RSA_0.25_1.1"],
        ["MiniBatchK-Means", "gas", "Swap"],
        ["TEG_Cosine_30", "electricity", False],
        ["TEG_Cosine_30", "electricity", "Avg"],
        ["TEG_Cosine_30", "electricity", "FDI0"],
        ["TEG_Cosine_30", "electricity", "FDI5"],
        ["TEG_Cosine_30", "electricity", "FDI10"],
        ["TEG_Cosine_30", "electricity", "FDI20"],
        ["TEG_Cosine_30", "electricity", "FDI30"],
        ["TEG_Cosine_30", "electricity", "Min-Avg"],
        ["TEG_Cosine_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "electricity", "Swap"],
        ["TEG_Cosine_30", "gas", False],
        ["TEG_Cosine_30", "gas", "Avg"],
        ["TEG_Cosine_30", "gas", "FDI0"],
        ["TEG_Cosine_30", "gas", "FDI5"],
        ["TEG_Cosine_30", "gas", "FDI10"],
        ["TEG_Cosine_30", "gas", "FDI20"],
        ["TEG_Cosine_30", "gas", "FDI30"],
        ["TEG_Cosine_30", "gas", "Min-Avg"],
        ["TEG_Cosine_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Cosine_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Cosine_30", "gas", "Swap"],
        ["TEG_Hamming_30", "electricity", False],
        ["TEG_Hamming_30", "electricity", "Avg"],
        ["TEG_Hamming_30", "electricity", "FDI0"],
        ["TEG_Hamming_30", "electricity", "FDI5"],
        ["TEG_Hamming_30", "electricity", "FDI10"],
        ["TEG_Hamming_30", "electricity", "FDI20"],
        ["TEG_Hamming_30", "electricity", "FDI30"],
        ["TEG_Hamming_30", "electricity", "Min-Avg"],
        ["TEG_Hamming_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "electricity", "Swap"],
        ["TEG_Hamming_30", "gas", False],
        ["TEG_Hamming_30", "gas", "Avg"],
        ["TEG_Hamming_30", "gas", "FDI0"],
        ["TEG_Hamming_30", "gas", "FDI5"],
        ["TEG_Hamming_30", "gas", "FDI10"],
        ["TEG_Hamming_30", "gas", "FDI20"],
        ["TEG_Hamming_30", "gas", "FDI30"],
        ["TEG_Hamming_30", "gas", "Min-Avg"],
        ["TEG_Hamming_30", "gas", "RSA_0.5_1.5"],
        ["TEG_Hamming_30", "gas", "RSA_0.25_1.1"],
        ["TEG_Hamming_30", "gas", "Swap"],
        ["TEG_KL_30", "electricity", False],
        ["TEG_KL_30", "electricity", "Avg"],
        ["TEG_KL_30", "electricity", "FDI0"],
        ["TEG_KL_30", "electricity", "FDI5"],
        ["TEG_KL_30", "electricity", "FDI10"],
        ["TEG_KL_30", "electricity", "FDI20"],
        ["TEG_KL_30", "electricity", "FDI30"],
        ["TEG_KL_30", "electricity", "Min-Avg"],
        ["TEG_KL_30", "electricity", "RSA_0.5_1.5"],
        ["TEG_KL_30", "electricity", "RSA_0.25_1.1"],
        ["TEG_KL_30", "electricity", "Swap"],
        ["TEG_KL_30", "gas", False],
        ["TEG_KL_30", "gas", "Avg"],
        ["TEG_KL_30", "gas", "FDI0"],
        ["TEG_KL_30", "gas", "FDI5"],
        ["TEG_KL_30", "gas", "FDI10"],
        ["TEG_KL_30", "gas", "FDI20"],
        ["TEG_KL_30", "gas", "FDI30"],
        ["TEG_KL_30", "gas", "Min-Avg"],
        ["TEG_KL_30", "gas", "RSA_0.5_1.5"],
        ["TEG_KL_30", "gas", "RSA_0.25_1.1"],
        ["TEG_KL_30", "gas", "Swap"],
        ["TEG_JS_30", "gas", False],
        ["TEG_JS_30", "gas", "Avg"],
        ["TEG_JS_30", "gas", "FDI0"],
        ["TEG_JS_30", "gas", "FDI5"],
        ["TEG_JS_30", "gas", "FDI10"],
        ["TEG_JS_30", "gas", "FDI20"],
        ["TEG_JS_30", "gas", "FDI30"],
        ["TEG_JS_30", "gas", "Min-Avg"],
        ["TEG_JS_30", "gas", "RSA_0.5_1.5"],
        ["TEG_JS_30", "gas", "RSA_0.25_1.1"],
        ["TEG_JS_30", "gas", "Swap"],
    ])
    def testIfFixedPrintMetricsWorks(self, detector, dataset, behaviour):
        detectorObject = DetectorFactory.create_detector(detector)

        f = io.StringIO()
        with redirect_stdout(f):
            detectorObject.print_metrics(9613, detector, behaviour, 11.24124, 21.4218656, 10, 5, 3, 2)
            out = f.getvalue()

        # The print metrics method has two \n before the first line with contents
        self.assertTrue("9613" in out.split("\n")[2])
        self.assertTrue(detector in out.split("\n")[3])
        self.assertTrue(str(behaviour) in out.split("\n")[4])
        self.assertTrue("11.24124" in out.split("\n")[5])
        self.assertTrue("21.4218656" in out.split("\n")[6])
        self.assertTrue("0.75" in out.split("\n")[7])
        self.assertTrue("10" in out.split("\n")[8])
        self.assertTrue("2" in out.split("\n")[9])
        self.assertTrue("5" in out.split("\n")[10])
        self.assertTrue("3" in out.split("\n")[11])

    @parameterized.expand([
        [100, 30, False],
        [100, 30, True],
        [100, 90, False],
        [100, 90, True]
    ])
    def testIfComputeOutliersWorks(self, testing_len, predictions, is_attack_behaviour):
        # IsolationForest detector because it does not override the compute_outliers method
        n_tp, n_tn, n_fp, n_fn = DetectorFactory.create_detector('IsolationForest').compute_outliers(testing_len, predictions,is_attack_behaviour)
        if is_attack_behaviour:
            self.assertEqual(predictions, n_tp)
            self.assertEqual(0, n_tn)
            self.assertEqual(0, n_fp)
            self.assertEqual(testing_len - predictions, n_fn)
        else:
            self.assertEqual(0, n_tp)
            self.assertEqual(testing_len - predictions, n_tn)
            self.assertEqual(predictions, n_fp)
            self.assertEqual(0, n_fn)


if __name__ == '__main__':
    unittest.main()
